---
# Fixtures file for puppet_spec_helper in the task: rake spec
fixtures:
  repositories:
    apt: https://github.com/puppetlabs/puppetlabs-apt
    epel: https://github.com/voxpupuli/puppet-epel
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core
